default momentum with start=100
ott-jax/ott pull request #155
Opened 2022-10-14 15:36 UTC by marcocuturi

refer to #151

2022-10-14 17:20 UTC, marcocuturi commented
fast test breaks on an instance with very small `epsilon` relative to distance matrix used. In that setting, 100 iterations is not enough for solution to be in a reasonable "bassin" and momentum rule diverges.... Maybe an interesting modification to consider would be to only enable adaptive momentum when iterate already has low error.

2022-10-15 09:26 UTC, marcocuturi commented
propose to fix this by introducing an `error_threshold` parameter that checks whether error has converged sufficiently to ensure momentum helps. Set that value conservatively at `1e-1` for now.

2022-10-15 15:25 UTC, marcocuturi commented
Observed that `momentum` can be too agressive even for "hard" instances. Fall back on an even more conservative setup were adaptive momentum is only considered after 300 iterations, with a lower `error_threshold`.

2022-10-17 10:12 UTC, michalk8 requested changes

2022-10-17 10:12 UTC, michalk8 commented on ott/core/momentum.py
> +        iteration >= self.start,
I'd prefer this using `jax.lax.cond` + `jnp.logical_and` (no need for 2 nested where's).

2022-10-17 12:36 UTC, merged