improve coverage
ott-jax/ott pull request #283
Opened 2023-02-14 16:14 UTC by giovp

remove coverage from `types.py` and init tests for `decomposition.py`, partially address #254 

Had some issues with passing correct arrays to `SparseCholesky` so could try to improve interface a bit.

2023-02-16 09:25 UTC, giovp commented
I'm not sure why tests are failing, seems pip can't resolve dependencies, shall I unpin up `scikit-sparse`

2023-02-16 09:59 UTC, michalk8 requested changes
We don't have CHOLMOD on the GPU server (yet), so tests there are disabled (via tox), that's why it fails. On all others, it should be fine.

2023-02-16 09:59 UTC, michalk8 commented on tests/math/decomposition_test.py
> +
Please add [this](https://github.com/ott-jax/ott/blob/main/tests/geometry/graph_test.py#L21)

2023-02-16 09:59 UTC, michalk8 commented on pyproject.toml
> +    "scikit-sparse>=0.4.6"
This is already handled in `tox`, please remove.

2023-02-16 14:21 UTC, michalk8 commented on .coveragerc
> +omit = src/ott/types.py
This is already specified in [pyproject.toml](https://github.com/ott-jax/ott/blob/main/pyproject.toml#L121).

2023-07-10 18:33 UTC, marcocuturi commented
@giovp could you take a look maybe? we might want to merge, because we want to increase coverage :)

2023-07-11 14:44 UTC, giovp commented
@marcocuturi resolved conflicts, any pointer on what else to be done LMK

2023-11-29 17:10 UTC, closed without merging