ENH: add doc for SinkhornOutput
ott-jax/ott pull request #287
Opened 2023-02-14 17:01 UTC by pierreablin

This adds a docstring to the `SinkhornOutput` class, which is often exposed to the user.

2023-02-15 14:18 UTC, michalk8 requested changes
Thanks Pierre! I think it would be best however to work on this in parallel in #284, since some attributes will be removed + documenting dataclasses is a bit different - wdyt?

2023-02-15 14:18 UTC, michalk8 commented on src/ott/solvers/linear/sinkhorn.py
> +  r"""Implements the problems.Transport interface, for a Sinkhorn solution.
No need for `r`

2023-02-15 14:18 UTC, michalk8 commented on src/ott/solvers/linear/sinkhorn.py
> +    f: jnp.ndarray, potential
Please remove all type hints from docstrings.

2023-02-15 14:18 UTC, michalk8 commented on src/ott/solvers/linear/sinkhorn.py
> +
Remove empty line.

2023-02-15 14:18 UTC, michalk8 commented on src/ott/solvers/linear/sinkhorn.py
> +    a: jnp.ndarray, marginals of the problem
Source marginals

2023-02-15 14:18 UTC, michalk8 commented on src/ott/solvers/linear/sinkhorn.py
> +    b: jnp.ndarray, marginals of the problem
Target marginals

2023-07-10 18:32 UTC, marcocuturi commented
@pierreablin could you take another look, in order to merge/close this?

2023-07-11 14:25 UTC, pierreablin commented
Actually seems like https://github.com/ott-jax/ott/commit/db9f58a13755901e877ececa6d2388dd9d62d6b1 makes this useless, right? If yes, we can close.

2024-06-05 16:08 UTC, michalk8 commented
Closing because of inactivity

2024-06-05 16:08 UTC, closed without merging