Possibility to compute multilple quantiles at once
ott-jax/ott pull request #382
Opened 2023-07-01 11:25 UTC by marcocuturi

This PR is a follow up to 
https://github.com/ott-jax/ott/discussions/373
This implements a ``quantiles`` function in the ``soft_sort`` module to return simultenaously multiple quantile values. Should be more efficient than the vmap proposed in the discussion, but will likely return very slightly different results.

2023-07-02 07:40 UTC, marcocuturi commented
numba, via jaxopt, seems to be causing the issue.

2023-07-03 21:48 UTC, merged

2023-07-03 21:56 UTC, michalk8 requested changes

2023-07-04 07:08 UTC, marcocuturi commented on src/ott/tools/soft_sort.py
> +    weights: vector of nonnegative weights, summing to :math:`1.0`, of the same
there's an argument for dropping the hyphen :) https://math.stackexchange.com/questions/3342643/nonnegative-vs-non-negative

2023-07-04 08:39 UTC, marcocuturi commented on tests/tools/soft_sort_test.py
> +    m2 = soft_sort.quantile(inputs, q=q, weight=None, axis=0)
thanks! I think this was naive byproduct of starting PR with 2 different interfaces (`quantile` and `quantiles`)

2023-07-04 08:41 UTC, marcocuturi commented on src/ott/tools/soft_sort.py
> +  ```
thanks!

2023-07-04 08:49 UTC, marcocuturi commented on src/ott/tools/soft_sort.py
> +      attribute :attr:`~ott.geometry.pointcloud.cost_fn` of
thanks

2023-07-04 08:51 UTC, marcocuturi commented on src/ott/tools/soft_sort.py
> +    q = jnp.array([0.2, 0.5, 0.8]) if q is None else jnp.atleast_1d(q)
I think it's also a question of being able to re-run by changing quantile values, without jitting again, pending that the number of quantiles does not change.