Add sparse Chebyshev approximation
ott-jax/ott pull request #502
Opened 2024-03-16 16:54 UTC by guillaumehu

In this PR, we modify the Chebyshev approximation used in the geodesic geometry to work with sparse BCOO graph.

- [ ] Sparse Laplacian fn
- [ ] Sparse Cheb approximation fn
- [ ] test heat kernel approx
- [ ] test that it integrates with Sinkhorn.

2024-03-17 17:07 UTC, guillaumehu commented on tests/geometry/geodesic_test.py
>      approx = geom.apply_kernel(jnp.eye(G.shape[0]))
The output here is not a BCOO, but a dense matrix. Is this what we want ?

2024-03-17 21:32 UTC, michalk8 requested changes

2024-03-17 21:32 UTC, michalk8 commented on src/ott/geometry/geodesic.py
> +    laplacian = inv_sqrt_deg @ laplacian @ inv_sqrt_deg
Think here we could also use `laplacian = data_inv[:, None] * laplacian * data_inv[None, :]`, should be a bit faster.

2024-03-17 22:44 UTC, guillaumehu commented on src/ott/geometry/geodesic.py
> +@jesp.sparsify
Perfect, I added this test! I had to raise the memory limit a little bit.

2024-03-17 22:51 UTC, guillaumehu commented
Thank you for reviewing the PR @michalk8 ! I made the suggested changes, let me know what you think.

2024-03-18 16:05 UTC, michalk8 approved these changes
Thanks a lot @guillaumehu , LGTM!

2024-03-18 16:05 UTC, merged